# Generated by Django 5.0.1 on 2024-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Categray',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
