# Generated by Django 5.0.1 on 2024-05-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_books_categray'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
